/**
 * diseaseNames.ts — 疾病名称标准化显示工具
 * 统一将缩写 key（如 "IBD"）转为标准全称（如 "Inflammatory Bowel Disease (IBD)"）
 * 中文映射内嵌，不依赖后端 API
 */

const API_BASE = import.meta.env.VITE_API_URL ?? "http://localhost:8000";

let displayMap: Record<string, string> | null = null;
let loading: Promise<void> | null = null;

/** 预加载显示名称映射（应用启动时调用一次） */
export function preloadDiseaseNames(): void {
  if (displayMap || loading) return;
  loading = fetch(`${API_BASE}/api/disease-display-names`)
    .then((r) => r.json())
    .then((data: Record<string, string>) => { displayMap = data; })
    .catch(() => { displayMap = {}; });
}

// ── 中文疾病名映射（内嵌，无需后端） ──────────────────────────────
const DISEASE_ZH: Record<string, string> = {
  "NC": "健康对照",
  "hematopoietic_stem_cell_transplantation": "造血干细胞移植",
  "Hematologic malignancy": "血液恶性肿瘤",
  "preterm infants": "早产儿",
  "chickenpox": "水痘",
  "UC": "溃疡性结肠炎",
  "obesity": "肥胖症",
  "c_difficile_infection": "艰难梭菌感染",
  "CD": "克罗恩病",
  "colorectal_cancer": "结直肠癌",
  "HIV": "HIV感染",
  "Non-CDI diarrhea control": "非CDI腹泻对照",
  "IBS": "肠易激综合征",
  "HIV-exposed uninfected": "HIV暴露未感染",
  "skin_condition": "皮肤疾病",
  "Acute myeloid leukemia": "急性髓系白血病",
  "adenoma": "腺瘤",
  "lactose_intolerance": "乳糖不耐受",
  "seasonal_allergies": "季节性过敏",
  "Lean": "消瘦",
  "ICU patient": "ICU患者",
  "acid_reflux": "胃酸反流",
  "LTACH patient": "长期急性护理患者",
  "severe acute malnutrition": "严重急性营养不良",
  "migraine": "偏头痛",
  "parkinson": "帕金森病",
  "h_pylori_infection": "幽门螺杆菌感染",
  "Food allergy": "食物过敏",
  "autoimmune": "自身免疫性疾病",
  "IBD": "炎症性肠病",
  "Type 1 diabetes": "1型糖尿病",
  "cholera": "霍乱",
  "NAFLD": "非酒精性脂肪肝",
  "fungal_overgrowth": "真菌过度生长",
  "asd": "自闭症谱系障碍",
  "thyroid": "甲状腺疾病",
  "asthma": "哮喘",
  "Acute Lymphoblastic Leukemia": "急性淋巴细胞白血病",
  "Epithelial Ovarian Cancer (EOC)": "上皮性卵巢癌",
  "lung_disease": "肺部疾病",
  "diarrhea": "腹泻",
  "Relapsing-remitting multiple sclerosis": "复发缓解型多发性硬化",
  "Small Intestinal Bacterial Overgrowth": "小肠细菌过度生长",
  "Type 2 diabetes Mellitus with Hyperlipidemia": "2型糖尿病伴高脂血症",
  "add_adhd": "注意力缺陷多动障碍",
  "Subjects at Risk for Metabolic Syndrome": "代谢综合征风险人群",
  "gastric_cancer": "胃癌",
  "Preterm neonate": "早产新生儿",
  "Type 2 diabetes": "2型糖尿病",
  "stunted": "发育迟缓",
  "COVID": "新冠感染",
  "COVIDrecovered": "新冠康复",
  "COPD": "慢性阻塞性肺病",
  "Breast Cancer": "乳腺癌",
  "Bipolar Disorder": "双相情感障碍",
  "Anorexia nervosa": "神经性厌食症",
  "Antibiotic-associated diarrhea": "抗生素相关腹泻",
  "Antibiotic-exposed NICU patient infant": "抗生素暴露NICU婴儿",
  "Asymptomatic C. difficile colonization": "无症状艰难梭菌定植",
  "ACF with polyp": "伴息肉异常隐窝灶",
  "ACF without polyp": "不伴息肉异常隐窝灶",
  "Abx": "抗生素使用",
  "Active pulmonary tuberculosis": "活动性肺结核",
  "Acute Infectious Diarrhea": "急性感染性腹泻",
  "Acute non-perforated appendicitis": "急性非穿孔性阑尾炎",
  "Advanced adenoma": "进展期腺瘤",
  "Chronic Fatigue Syndrome / Myalgic Encephalomyelitis": "慢性疲劳综合征",
  "Chronic Superficial gastritis": "慢性浅表性胃炎",
  "Chronic alcohol overconsumption": "慢性过量饮酒",
  "cirrhosis": "肝硬化",
  "cystic_fibrosis": "囊性纤维化",
  "eczema": "湿疹",
  "esophageal_cancer": "食管癌",
  "fatty_liver": "脂肪肝",
  "gestational_diabetes": "妊娠糖尿病",
  "gout": "痛风",
  "hepatitis": "肝炎",
  "hepatocellular_carcinoma": "肝细胞癌",
  "hypertension": "高血压",
  "kidney_disease": "肾脏疾病",
  "liver_cancer": "肝癌",
  "liver_disease": "肝脏疾病",
  "melanoma": "黑色素瘤",
  "metabolic_syndrome": "代谢综合征",
  "multiple_sclerosis": "多发性硬化",
  "necrotizing_enterocolitis": "坏死性小肠结肠炎",
  "pancreatitis": "胰腺炎",
  "pancreatic_cancer": "胰腺癌",
  "periodontitis": "牙周炎",
  "pneumonia": "肺炎",
  "pre-eclampsia": "子痫前期",
  "prostate_cancer": "前列腺癌",
  "psoriasis": "银屑病",
  "rheumatoid_arthritis": "类风湿关节炎",
  "schizophrenia": "精神分裂症",
  "sepsis": "脓毒症",
  "systemic_lupus_erythematosus": "系统性红斑狼疮",
  "IGA GLOMERULONEPHRITIS": "IgA肾病",
  "Non-alcoholic steatohepatitis": "非酒精性脂肪性肝炎",
  "Nonalcoholic Fatty Liver Disease": "非酒精性脂肪肝病",
  "Overweight": "超重",
  "Underweight": "体重不足",
  "allergic_rhinitis": "过敏性鼻炎",
  "celiac_disease": "乳糜泻",
  "depression": "抑郁症",
  "epilepsy": "癫痫",
  "chronic_kidney_disease": "慢性肾脏病",
  "heart_failure": "心力衰竭",
  "coronary_artery_disease": "冠心病",
  "stroke": "脑卒中",
  "Alzheimer": "阿尔茨海默病",
  "dementia": "痴呆",
  "anxiety": "焦虑症",
  "PCOS": "多囊卵巢综合征",
  "endometriosis": "子宫内膜异位症",
  "preeclampsia": "子痫前期",
  "premature_birth": "早产",
  "malnutrition": "营养不良",
  "kwashiorkor": "夸希奥科病",
  "marasmus": "消瘦症",
  "Short Bowel Syndrome": "短肠综合征",
  "Sjogren'S Syndrome": "干燥综合征",
  "Spinal Cord Injury": "脊髓损伤",
  "Spontaneous Intestinal Perforation": "自发性肠穿孔",
  "Strongyloides Stercoralis": "粪类圆线虫感染",
  "Superficial Gastritis": "浅表性胃炎",
  "Traveler": "旅行者腹泻",
  "Tuberculosis": "结核病",
  "Type 2 Diabetes With Obesity": "2型糖尿病伴肥胖",
  "Undernourished": "营养不良",
  "Advanced Gastric Cancer": "进展期胃癌",
  "Alcohol Use Disorder": "酒精使用障碍",
  "Atopic Dermatitis": "特应性皮炎",
  "Behcet's Disease": "白塞病",
  "Brain Tumor": "脑肿瘤",
  "Cachexia": "恶病质",
  "Celiac Disease": "乳糜泻",
  "Cerebral Palsy": "脑瘫",
  "Cholangiocarcinoma": "胆管癌",
  "Chronic Hepatitis B": "慢性乙型肝炎",
  "Chronic Liver Disease": "慢性肝病",
  "Clostridioides Difficile Infection": "艰难梭菌感染",
  "Constipation": "便秘",
  "Cystic Fibrosis": "囊性纤维化",
  "Down Syndrome": "唐氏综合征",
  "Drug-resistant Epilepsy": "难治性癫痫",
  "Dyslipidemia": "血脂异常",
  "End Stage Renal Disease": "终末期肾病",
  "Familial Mediterranean Fever": "家族性地中海热",
  "Functional Gastrointestinal Disorder": "功能性胃肠病",
  "Gallstone": "胆结石",
  "Gastric Ulcer": "胃溃疡",
  "Graves Disease": "格雷夫斯病",
  "Hashimoto Thyroiditis": "桥本甲状腺炎",
  "Heart Failure": "心力衰竭",
  "Henoch-Schonlein Purpura": "过敏性紫癜",
  "Hepatic Encephalopathy": "肝性脑病",
  "Hepatitis B": "乙型肝炎",
  "Hepatitis C": "丙型肝炎",
  "Hepatocellular Carcinoma": "肝细胞癌",
  "Infant Colic": "婴儿肠绞痛",
  "Infertility": "不孕不育",
  "Kawasaki Disease": "川崎病",
  "Kidney Stone": "肾结石",
  "Kwashiorkor": "夸希奥科病",
  "Laryngeal Cancer": "喉癌",
  "Liver Cirrhosis": "肝硬化",
  "Lung Cancer": "肺癌",
  "Lupus Nephritis": "狼疮性肾炎",
  "Major Depressive Disorder": "重度抑郁症",
  "Morbid Obesity": "病态肥胖",
  "Multiple Myeloma": "多发性骨髓瘤",
  "Myasthenia Gravis": "重症肌无力",
  "Necrotizing Enterocolitis": "坏死性小肠结肠炎",
  "Nephrotic Syndrome": "肾病综合征",
  "Non-Hodgkin Lymphoma": "非霍奇金淋巴瘤",
  "Oral Cancer": "口腔癌",
  "Osteoarthritis": "骨关节炎",
  "Osteoporosis": "骨质疏松",
  "Pancreatic Cancer": "胰腺癌",
  "Peptic Ulcer": "消化性溃疡",
  "Peritoneal Dialysis": "腹膜透析",
  "Polycystic Ovary Syndrome": "多囊卵巢综合征",
  "Primary Biliary Cholangitis": "原发性胆汁性胆管炎",
  "Primary Sclerosing Cholangitis": "原发性硬化性胆管炎",
  "Prostate Cancer": "前列腺癌",
  "Recurrent C. Difficile Infection": "复发性艰难梭菌感染",
  "Renal Cell Carcinoma": "肾细胞癌",
  "Rheumatoid Arthritis": "类风湿关节炎",
  "Sarcoidosis": "结节病",
  "Schizophrenia": "精神分裂症",
  "Sepsis": "脓毒症",
  "Sickle Cell Disease": "镰状细胞病",
  "Small Cell Lung Cancer": "小细胞肺癌",
  "Systemic Sclerosis": "系统性硬化症",
  "Ulcerative Colitis": "溃疡性结肠炎",
  "Urinary Tract Infection": "尿路感染",
  "Vaginal Dysbiosis": "阴道菌群失调",
  "Wilson Disease": "威尔逊病",
  "PPIpost": "PPI使用后",
  "PPIpre": "PPI使用前",
  "Intestinal Metaplasia": "肠上皮化生",
  "LTACH Control": "长期急性护理对照",
  "LTACH patient": "长期急性护理患者",
  "Functional Gastrointestinal Disorders": "功能性胃肠病",
  "Gastritis": "胃炎",
  "NAFL": "非酒精性脂肪肝",
  "Vesicoureteral Reflux": "膀胱输尿管反流",
  "Neuromyelitis Optica": "视神经脊髓炎",
  "Chronic Critical Illness (CCI)": "慢性危重症",
  "Nursing Home Older Adults": "养老院老年人",
  "Fibromyalgia": "纤维肌痛",
  "Bilateral Bronchopneumonia": "双侧支气管肺炎",
  "Primary Biliary Cirrhosis": "原发性胆汁性肝硬化",
  "Non-Small Cell Lung Cancer": "非小细胞肺癌",
  "Chronic Constipation": "慢性便秘",
  "Allergic": "过敏",
  "Diarrhea-predominant IBS": "腹泻型肠易激综合征",
  "Colorectal Adenoma": "结直肠腺瘤",
  "Colorectal Cancer": "结直肠癌",
  "Coronary Artery Disease": "冠心病",
  "Dental Caries": "龋齿",
  "Diabetic Nephropathy": "糖尿病肾病",
  "Diabetic Retinopathy": "糖尿病视网膜病变",
  "Diverticulitis": "憩室炎",
  "Eating Disorder": "进食障碍",
  "Endometrial Cancer": "子宫内膜癌",
  "Familial Adenomatous Polyposis": "家族性腺瘤性息肉病",
  "Fatty Liver Disease": "脂肪肝病",
  "Gestational Diabetes": "妊娠糖尿病",
  "Graft-versus-Host Disease": "移植物抗宿主病",
  "Graves' Disease": "格雷夫斯病",
  "HIV Infection": "HIV感染",
  "Henoch-Schönlein Purpura": "过敏性紫癜",
  "Hyperuricemia": "高尿酸血症",
  "Hypertension": "高血压",
  "IgA Nephropathy": "IgA肾病",
  "Juvenile Idiopathic Arthritis": "幼年特发性关节炎",
  "Liver Transplant": "肝移植",
  "Membranous Nephropathy": "膜性肾病",
  "Metabolic Syndrome": "代谢综合征",
  "Minimal Change Disease": "微小病变肾病",
  "Moyamoya Disease": "烟雾病",
  "Multiple Sclerosis": "多发性硬化",
  "Myocardial Infarction": "心肌梗死",
  "Neonatal Sepsis": "新生儿脓毒症",
  "Neuroblastoma": "神经母细胞瘤",
  "Obesity": "肥胖症",
  "Oral Squamous Cell Carcinoma": "口腔鳞状细胞癌",
  "Overweight": "超重",
  "Parkinson's Disease": "帕金森病",
  "Peritonitis": "腹膜炎",
  "Polycystic Kidney Disease": "多囊肾病",
  "Post-transplant": "移植后",
  "Preeclampsia": "子痫前期",
  "Psoriatic Arthritis": "银屑病关节炎",
  "Renal Transplant": "肾移植",
  "Rett Syndrome": "瑞特综合征",
  "Spondyloarthritis": "脊柱关节炎",
  "Thyroid Cancer": "甲状腺癌",
  "Tourette Syndrome": "图雷特综合征",
  "Ulcerative Colitis": "溃疡性结肠炎",
  "Urolithiasis": "尿路结石",
  "Vitiligo": "白癜风",
  // ── 补全全部 125 个缺失翻译（2026-04-05） ──
  "Chronic Fatigue Syndrome / Myalgic Encephalomyelitis (CFS/ME)": "慢性疲劳综合征/肌痛性脑脊髓炎",
  "Compulsory drug abstinence": "强制戒毒",
  "Critically ill patients with acute respiratory failure": "急性呼吸衰竭危重患者",
  "Familial adenomatous Polyposis": "家族性腺瘤性息肉病",
  "Fecal occult blood positive,without severe underlying bowel disease": "粪便潜血阳性（无严重肠病）",
  "Functional constipation": "功能性便秘",
  "Functional_dyspepsia": "功能性消化不良",
  "GC-induced obesity": "糖皮质激素诱导肥胖",
  "Gestational diabetes mellitus": "妊娠期糖尿病",
  "HBV": "乙型肝炎病毒感染",
  "HPV-related gynecologic cancers": "HPV相关妇科肿瘤",
  "Hemodialysis": "血液透析",
  "Hirschsprung-associated enterocolitis": "先天性巨结肠相关小肠结肠炎",
  "Hirschsprungs disease without enterocolitis": "先天性巨结肠（无小肠结肠炎）",
  "IBS-D": "腹泻型肠易激综合征",
  "IgA glomerulonephritis": "IgA肾小球肾炎",
  "Infantile cholestasis": "婴儿胆汁淤积症",
  "Kidney Stone": "肾结石",
  "LTACH KPC_POSITIVE": "长期急性护理KPC阳性",
  "LTACH control": "长期急性护理对照",
  "Long-term PPI use": "长期PPI使用",
  "Long-term PPI use and cirrhosis": "长期PPI使用合并肝硬化",
  "Lung cancer": "肺癌",
  "Major Depressive Disorder (MDD)": "重度抑郁症",
  "Malabsorptive": "吸收不良",
  "MalariaPositivos": "疟疾阳性",
  "MalariaPositivos+helminth_infection": "疟疾阳性合并蠕虫感染",
  "Methadone maintenance treatment patient": "美沙酮维持治疗患者",
  "Multiple sclerosis": "多发性硬化",
  "NASH": "非酒精性脂肪性肝炎",
  "NCD_Ampicillin": "非CDI腹泻（氨苄西林）",
  "NCD_Cocktail": "非CDI腹泻（混合抗生素）",
  "NCD_Metronidazole": "非CDI腹泻（甲硝唑）",
  "NCD_Neomycin": "非CDI腹泻（新霉素）",
  "NCD_Vancomycin": "非CDI腹泻（万古霉素）",
  "Narcolepsy": "发作性睡病",
  "Necrotizing enterocolitis": "坏死性小肠结肠炎",
  "Neuromyelitis optica": "视神经脊髓炎",
  "No_Fecal occult blood positive": "粪便潜血阴性",
  "Non-T2D": "非2型糖尿病",
  "Non-abstinent drug user": "未戒断药物使用者",
  "Non-celiac gluten wheat sensitivity individual": "非乳糜泻麸质敏感",
  "Non-haematological malignancy": "非血液系统恶性肿瘤",
  "Non-kwashiorkor co-twin": "非夸希奥科病双胞胎",
  "Non-small cell lung cancer": "非小细胞肺癌",
  "Nursing home older adults": "养老院老年人",
  "Obstructive sleep apnea-After": "阻塞性睡眠呼吸暂停（治疗后）",
  "Obstructive sleep apnea-Before": "阻塞性睡眠呼吸暂停（治疗前）",
  "Other allergy": "其他过敏",
  "PSC-IBD": "原发性硬化性胆管炎合并IBD",
  "Perioperative bowel resection patient": "围术期肠切除患者",
  "Pouch": "储袋（回肠储袋）",
  "Prader-Willi syndrome": "普拉德-威利综合征",
  "Primary Progressive Multiple Sclerosis": "原发进展型多发性硬化",
  "Primary Sclerosing Cholangitis + UC": "原发性硬化性胆管炎合并溃疡性结肠炎",
  "Psychiatric_disorder": "精神障碍",
  "RA-related (undefined subtype)": "类风湿关节炎相关（亚型未定义）",
  "Refractory_epilepsy": "难治性癫痫",
  "Rett syndrome (RTT)": "瑞特综合征",
  "Secondary Progressive Multiple Sclerosis": "继发进展型多发性硬化",
  "Sjogren's syndrome": "干燥综合征",
  "Spontaneous intestinal perforation": "自发性肠穿孔",
  "Strongyloides stercoralis": "粪类圆线虫感染",
  "Superficial gastritis": "浅表性胃炎",
  "Type 2 diabetes with obesity": "2型糖尿病伴肥胖",
  "advanced gastric_cancer": "进展期胃癌",
  "alcohol use disorder": "酒精使用障碍",
  "alcoholic hepatitis": "酒精性肝炎",
  "alcoholic liver_disease": "酒精性肝病",
  "allergic": "过敏",
  "allergic colitis": "过敏性结肠炎",
  "allergic rhinitis": "过敏性鼻炎",
  "aplastic anemia": "再生障碍性贫血",
  "atrophic gastritis": "萎缩性胃炎",
  "autoimmune thyloiditis": "自身免疫性甲状腺炎",
  "bilateral bronchopneumonia": "双侧支气管肺炎",
  "cardiovascular_disease": "心血管疾病",
  "cerebral infarction": "脑梗死",
  "chronic constipation": "慢性便秘",
  "chronic critical illness (CCI)": "慢性危重症",
  "colorectal polyps": "结直肠息肉",
  "compensated cirrhosis": "代偿期肝硬化",
  "coronary artery disease (CAD)": "冠状动脉疾病",
  "diabetes": "糖尿病",
  "dichorionic concordant twin": "双绒毛膜一致性双胎",
  "diet_intervention": "饮食干预",
  "diffuse large B-cell lymphoma (DLBCL)": "弥漫大B细胞淋巴瘤",
  "early gastric_cancer": "早期胃癌",
  "eosinophilic esophagitis": "嗜酸性食管炎",
  "gallstone disease": "胆石症",
  "gastritis": "胃炎",
  "h_pylori_infection successful eradication": "幽门螺杆菌根除成功",
  "helminth_infection": "蠕虫感染",
  "high risk for asthma": "哮喘高风险",
  "hyperlipidemia": "高脂血症",
  "hypertension patients with cognitive impairment": "高血压伴认知障碍",
  "intestinal metaplasia": "肠上皮化生",
  "lipid metabolism disorder": "脂质代谢异常",
  "localized scleroderma": "局限性硬皮病",
  "low risk for asthma": "哮喘低风险",
  "metabolic syndrome": "代谢综合征",
  "metabolic syndrome with severe obesity": "代谢综合征伴严重肥胖",
  "monochorionic concordant twin": "单绒毛膜一致性双胎",
  "myocardial infarction": "心肌梗死",
  "neurotypical": "神经发育正常",
  "obesity with NAFLD": "肥胖伴非酒精性脂肪肝",
  "obesity without NAFLD": "肥胖不伴非酒精性脂肪肝",
  "osteoporosis": "骨质疏松",
  "persistent diarrhea": "持续性腹泻",
  "placebo-responsive individual": "安慰剂应答者",
  "post-Helicobacter pylori eradication": "幽门螺杆菌根除后",
  "prediabetes": "糖尿病前期",
  "primary biliary cirrhosis": "原发性胆汁性肝硬化",
  "primary immune thrombocytopenia": "原发性免疫性血小板减少症",
  "prostate cancer": "前列腺癌",
  "prostatic hypertrophy": "前列腺增生",
  "rheumatoid arthritis": "类风湿关节炎",
  "secondary hypertension": "继发性高血压",
  "severe gastritis": "重度胃炎",
  "spondyloarthritis": "脊柱关节炎",
  "systemic scleroderma": "系统性硬皮病",
  "thyloid carcinoma": "甲状腺癌",
  "undernourished infants": "营养不良婴儿",
  "underweight": "体重不足",
  "vesicoureteral reflux": "膀胱输尿管反流",
  "without severe underlying bowel disease": "无严重基础肠病",
};

/**
 * 获取疾病的标准化显示名称（仅全称，不附加缩写括号）
 * - 有映射 → 返回标准全称（如 "Colorectal Cancer"）
 * - 无映射 → 返回原始 key，下划线替换为空格，首字母大写
 */
export function diseaseDisplayName(key: string): string {
  const name = displayMap && displayMap[key] ? displayMap[key] : key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  return name;
}

// Build normalized lookup for fuzzy matching (once)
// 构建归一化查找表用于模糊匹配（仅构建一次）
const _DISEASE_ZH_NORM: Record<string, string> = {};
for (const [k, v] of Object.entries(DISEASE_ZH)) {
  _DISEASE_ZH_NORM[k.toLowerCase().replace(/[_\s-]+/g, " ").trim()] = v;
}

function lookupDiseaseZh(key: string): string | undefined {
  // 1. Exact match
  if (DISEASE_ZH[key]) return DISEASE_ZH[key];
  // 2. Normalized match (case-insensitive, underscore/hyphen → space)
  const norm = key.toLowerCase().replace(/[_\s-]+/g, " ").trim();
  return _DISEASE_ZH_NORM[norm];
}

/**
 * 获取疾病的国际化显示名称
 * locale === "zh" 时返回中文名（内嵌映射），否则返回英文标准名
 */
export function diseaseDisplayNameI18n(key: string, locale: string): string {
  if (locale === "zh") {
    const zh = lookupDiseaseZh(key);
    if (zh) return zh;
  }
  return diseaseDisplayName(key);
}

/** 获取简短显示名（用于按钮/标签等空间有限的场景） */
export function diseaseShortName(key: string, maxLen = 30): string {
  const full = diseaseDisplayName(key);
  return full.length > maxLen ? full.slice(0, maxLen - 1) + "…" : full;
}

/** 国际化简短显示名 */
export function diseaseShortNameI18n(key: string, locale: string, maxLen = 30): string {
  const full = diseaseDisplayNameI18n(key, locale);
  return full.length > maxLen ? full.slice(0, maxLen - 1) + "…" : full;
}
